apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: lu6xx5p5h-nodejs 
  janus-idp.io/tekton: lu6xx5p5h-nodejs
  backstage.io/kubernetes-id: lu6xx5p5h-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lu6xx5p5h-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml